name: Deploy

on:
  release:
    types:
      - published

jobs:
  build:
    if: github.repository == 'lovemefan/SenseVoice-python'
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: |
            git fetch --prune --unshallow            

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U twine wheel

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*      

      - name: Publish package to PyPI
        if: github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}